### ISSUE TITLE
Dependabot vulnerability scan

### ISSUE THREAD

**Issue by bthomee** [multimediaeval/multimediaeval.github.io#43]
Dependabot revealed two security alerts [1, 2] due to outdated dependencies in the assets/package-lock.json. Given that there is not a corresponding package.json file, I wonder whether this file got accidentally pushed to the repo.

To resolve this issue, please verify if the assets/package-lock.json is necessary.
* If it is not, please delete it. Consider adding the file to .gitignore to prevent it from being added in the future.
* If it is needed, then figure out why the associated package.json is not included in the repo. For example, running `npm audit fix` can help find compatible dependency upgrades, but because the package.json is missing it cannot do so.

[1] https://github.com/multimediaeval/multimediaeval.github.io/network/alert/assets/package-lock.json/bl/open
[2] https://github.com/multimediaeval/multimediaeval.github.io/network/alert/assets/package-lock.json/decompress/open

**Comment by ricoms** [comment]
Sorry for taking so long. the files `package.json` (available at `assets/` on `gh-page` branch) and `package-lock.json` were not required for the final website to be built. Those and other deprecated files were removed from `gh-page` branch, doing that it also removed them from `master` branch and those security warnings are now non-existent.
